### ISSUE TITLE
Moderation Interface

### ISSUE THREAD

**Issue by ericuldall** [adtac/commento#189]
Under features it says:

> Review and approve or delete comments through the moderation interface

I don't see any documentation on how to use this moderation interface. Can you provide some?

**Comment by adtac** [comment]
He @ericuldall! The moderation interface is a part of a rewrite I've been doing for the past few months. The current default branch (`v0`) will be retired soon. You can follow the development [here](https://gitlab.com/commento/commento-ce). We're #movingtogitlab too :)

However, here's a sneak peek into what it looks like:

![screenshot from 2018-06-08 09-12-27](https://user-images.githubusercontent.com/7521600/41138014-16c58f70-6afc-11e8-8905-b9ee942588a5.png)

^ the blue background comments are the new ones; you can approve them or delete them

**Comment by ericuldall** [comment]
Is there a docker image built with the latest dev version I can try?

**Comment by ericuldall** [comment]
I'm getting the following error (running in kubernetes):
```
[ERROR] router.go:29 serveRoutes(): cannot start server: listen tcp: address 0.0.0.0:tcp://10.43.245.163:80: too many colons in address
```

Sample of my deployment:
```
---
  apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    name: "commento-test"
    namespace: "stage"
  spec:
    progressDeadlineSeconds: 180
    replicas: 1
    strategy:
      rollingUpdate:
        maxUnavailable: 30%
        maxSurge: 50%
    template:
      metadata:
        labels:
          name: "commento"
      spec:
        containers:
          -
            name: "commento"
            image: "registry.gitlab.com/commento/commento-ce"
            env:
              - name: COMMENTO_ORIGIN
                value: http://[REDACTED]
              - name: COMMENTO_POSTGRES
                value: postgres://postgres:postgres@localhost:5432/commento?sslmode=disable
            ports:
              -
                containerPort: 8080
          -
            name: "postgres"
            image: "postgres"
            env:
              - name: POSTGRES_DB
                value: commento
              - name: POSTGRES_USER
                value: postgres
              - name: POSTGRES_PASSWORD
                value: postgres
            ports:
              -
                containerPort: 5432
```
